# SmartCache Configuration File
# Generated on 2025-08-04

# Default network for contract operations
# Options: arbitrum-sepolia, arbitrum-one, arbitrum-nova, localhost
network = "arbitrum-sepolia"

# Your wallet address that deployed the contracts, this is required for all operations
deployed_by = "0x37d009b82c32f49ec25cC98b2F47B2503886389a"

# Optional: Default contract address
# If specified, you can run 'smart-cache add' without providing an address
contract_address = "0x100487b1f93c5ed3f1ada6fc10e4b248af185bf6"

# Optional: Default contract metadata
# name = "MyContract"
# description = "Contract description"
version = "1.0.0"

# CLI behavior settings
interactive = false

# Optional: Custom metadata (add any additional fields you need)
# [metadata]
# author = "Your Name"
# license = "MIT"
# tags = ["defi", "nft"]
